default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: canvas_development

test:
  <<: *default
  database: canvas_test

production:
  <<: *default
  database: canvas_production
  username: canvas
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
